### ISSUE TITLE
Master is Pointing at 1.0.4

### ISSUE THREAD

**Issue by todd** [rubiety/nilify_blanks#21]
The version specified in `version.rb` on master is pointing at 1.0.4 while the current release appears to be 1.1.0. I'm not sure if something got overwritten at some point or 1.1.0 was tagged from a non-master branch, but you should probably conduct an audit before you cut a new version to see if there are any differences between 1.1.0 and master.

**Comment by rubiety** [comment]
Yep this was a missed push on my part. Luckily the only commit missing was the one that bumped the version and tagged the release. Pushed and now it's consistent; thanks for letting me know.

**Comment by todd** [comment]
:+1:
