### ISSUE TITLE
Bug in define_nilify_blank_methods

### ISSUE THREAD

**Issue by cdc1996** [rubiety/nilify_blanks#36]
In file lib/nilify_blanks.rb

Line 54: 
`return if @nilify_blank_methods_generated`

Line 78:
`@nilify_blanks_methods_generated = true`

Is line 54 missing an 's'

**Comment by semicolonandsons** [comment]
Just noticed the same. The presence of this bug for this many years suggests that those two lines of code aren't useful and can be removed.

**Comment by rubiety** [comment]
Fixed in PR #44, closing.
