### ISSUE TITLE
Release 1.3.0 to gem repository

### ISSUE THREAD

**Issue by contentfree** [rubiety/nilify_blanks#41]
It looks like the version was bumped to 1.3.0 a while ago, but a release was never made to rubygems. Please consider releasing.

**Comment by rubiety** [comment]
Hmm... v1.3.0 has been on rubygems for a while: https://rubygems.org/gems/nilify_blanks

<img width="680" alt="screen shot 2019-02-28 at 14 56 28" src="https://user-images.githubusercontent.com/5492/53604388-27644b80-3b69-11e9-8617-2328d0139491.png">

@contentfree What version are you seeing?

**Comment by espen** [comment]
I guess this could be closed.
