### ISSUE TITLE
Impossible to override default settings

### ISSUE THREAD

**Issue by BuonOmo** [rubiety/nilify_blanks#45]
Using it, I stumbled over what looks like a major issue:

```ruby
# initializer
ActiveSupport.on_load(:active_record) { ActiveRecord::Base.nilify_blanks }

# some class
class Post < ActiveRecord::Base
  nifily_blanks except: %i(citation) # Never taken into account.
end
```

I think we should embrace the rails callbacks way:

> Calling the same callback multiple times will overwrite previous callback definitions.

What do you think?

----

Another note, using `nilify_blanks` will remove existing callbacks. Shouldn't we prevent this? Or at least warn users.

**Comment by rubiety** [comment]
I believe this has been fixed as part of recent restructuring, and in commit 15f94d6. Feel free to try `v1.4.0` and see if it has fixed your problem.
